import { createElement } from "react";

const WHITE_PALETTE = {
  primary: "#ffffff",
  secondary: "#f8fafc",
  accent: "#e2e8f0",
  shadow: "#cbd5f5",
  stroke: "#0f172a",
};

const BLACK_PALETTE = {
  primary: "#1f2937",
  secondary: "#111827",
  accent: "#374151",
  shadow: "#0f172a",
  stroke: "#0f172a",
};

export const PIECE_LABELS = {
  p: "pawn",
  r: "rook",
  n: "knight",
  b: "bishop",
  q: "queen",
  k: "king",
};

const withSvg = (elements) =>
  createElement(
    "svg",
    {
      viewBox: "0 0 64 64",
      role: "img",
      "aria-hidden": "true",
      focusable: "false",
      className: "h-full w-full",
    },
    ...(Array.isArray(elements) ? elements : [elements])
  );

const SPRITES = {
  p: (palette) =>
    withSvg([
      createElement("circle", {
        key: "head",
        cx: 32,
        cy: 18,
        r: 11,
        fill: palette.primary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("rect", {
        key: "torso",
        x: 22,
        y: 30,
        width: 20,
        height: 12,
        rx: 6,
        fill: palette.secondary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("rect", {
        key: "waist",
        x: 16,
        y: 44,
        width: 32,
        height: 10,
        rx: 4,
        fill: palette.primary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("rect", {
        key: "base",
        x: 12,
        y: 52,
        width: 40,
        height: 6,
        rx: 3,
        fill: palette.shadow,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
    ]),
  r: (palette) =>
    withSvg([
      createElement("rect", {
        key: "base",
        x: 12,
        y: 50,
        width: 40,
        height: 6,
        rx: 3,
        fill: palette.shadow,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("rect", {
        key: "foot",
        x: 18,
        y: 44,
        width: 28,
        height: 8,
        rx: 2,
        fill: palette.primary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("rect", {
        key: "body",
        x: 18,
        y: 20,
        width: 28,
        height: 24,
        rx: 4,
        fill: palette.secondary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("rect", {
        key: "top",
        x: 16,
        y: 12,
        width: 32,
        height: 8,
        fill: palette.primary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("rect", {
        key: "left",
        x: 14,
        y: 8,
        width: 8,
        height: 6,
        fill: palette.primary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("rect", {
        key: "mid",
        x: 28,
        y: 8,
        width: 8,
        height: 6,
        fill: palette.primary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("rect", {
        key: "right",
        x: 42,
        y: 8,
        width: 8,
        height: 6,
        fill: palette.primary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
    ]),
  n: (palette) =>
    withSvg([
      createElement("path", {
        key: "silhouette",
        d: "M18 48c8-6 8-10 8-16 0-4-2-8-2-8l12 6 8-12-18-10-12 16v24z",
        fill: palette.primary,
        stroke: palette.stroke,
        strokeWidth: 4,
        strokeLinejoin: "round",
      }),
      createElement("path", {
        key: "mane",
        d: "M30 18l-8-6-8 10",
        stroke: palette.stroke,
        strokeWidth: 4,
        strokeLinecap: "round",
        strokeLinejoin: "round",
        fill: "none",
      }),
      createElement("path", {
        key: "bridle",
        d: "M34 22c-2 4-6 6-10 8",
        stroke: palette.accent,
        strokeWidth: 3,
        strokeLinecap: "round",
        fill: "none",
      }),
      createElement("circle", {
        key: "eye",
        cx: 40,
        cy: 18,
        r: 3,
        fill: palette.accent,
        stroke: palette.stroke,
        strokeWidth: 2,
      }),
      createElement("rect", {
        key: "saddle",
        x: 18,
        y: 38,
        width: 20,
        height: 8,
        rx: 4,
        fill: palette.secondary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("rect", {
        key: "base",
        x: 12,
        y: 50,
        width: 40,
        height: 6,
        rx: 3,
        fill: palette.shadow,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
    ]),
  b: (palette) =>
    withSvg([
      createElement("ellipse", {
        key: "body",
        cx: 32,
        cy: 24,
        rx: 12,
        ry: 16,
        fill: palette.primary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("path", {
        key: "cut",
        d: "M26 20l12 12M38 20L26 32",
        stroke: palette.stroke,
        strokeWidth: 4,
        strokeLinecap: "round",
      }),
      createElement("rect", {
        key: "sash",
        x: 22,
        y: 40,
        width: 20,
        height: 10,
        rx: 5,
        fill: palette.secondary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("rect", {
        key: "base",
        x: 18,
        y: 50,
        width: 28,
        height: 6,
        rx: 3,
        fill: palette.shadow,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("circle", {
        key: "cap",
        cx: 32,
        cy: 10,
        r: 4,
        fill: palette.primary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
    ]),
  q: (palette) =>
    withSvg([
      createElement("path", {
        key: "skirt",
        d: "M14 50c4-16 10-24 18-24s14 8 18 24",
        fill: palette.primary,
        stroke: palette.stroke,
        strokeWidth: 4,
        strokeLinejoin: "round",
      }),
      createElement("rect", {
        key: "corset",
        x: 24,
        y: 26,
        width: 16,
        height: 12,
        rx: 4,
        fill: palette.secondary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("path", {
        key: "crown",
        d: "M18 20l4-6 6 6 6-6 6 6 4-6 4 6",
        fill: palette.primary,
        stroke: palette.stroke,
        strokeWidth: 4,
        strokeLinejoin: "round",
        strokeLinecap: "round",
      }),
      createElement("circle", {
        key: "gem-left",
        cx: 20,
        cy: 12,
        r: 3,
        fill: palette.accent,
        stroke: palette.stroke,
        strokeWidth: 3,
      }),
      createElement("circle", {
        key: "gem-center",
        cx: 32,
        cy: 10,
        r: 4,
        fill: palette.accent,
        stroke: palette.stroke,
        strokeWidth: 3,
      }),
      createElement("circle", {
        key: "gem-right",
        cx: 44,
        cy: 12,
        r: 3,
        fill: palette.accent,
        stroke: palette.stroke,
        strokeWidth: 3,
      }),
      createElement("rect", {
        key: "base",
        x: 18,
        y: 50,
        width: 28,
        height: 6,
        rx: 3,
        fill: palette.shadow,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
    ]),
  k: (palette) =>
    withSvg([
      createElement("path", {
        key: "cloak",
        d: "M20 50c2-10 6-18 12-18s10 8 12 18",
        fill: palette.primary,
        stroke: palette.stroke,
        strokeWidth: 4,
        strokeLinejoin: "round",
      }),
      createElement("rect", {
        key: "torso",
        x: 26,
        y: 24,
        width: 12,
        height: 16,
        rx: 4,
        fill: palette.secondary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("path", {
        key: "cross",
        d: "M32 6v12M26 12h12",
        stroke: palette.stroke,
        strokeWidth: 4,
        strokeLinecap: "round",
      }),
      createElement("rect", {
        key: "crown",
        x: 26,
        y: 18,
        width: 12,
        height: 6,
        rx: 3,
        fill: palette.primary,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
      createElement("path", {
        key: "shoulders",
        d: "M18 44h28",
        stroke: palette.stroke,
        strokeWidth: 4,
        strokeLinecap: "round",
      }),
      createElement("rect", {
        key: "base",
        x: 18,
        y: 50,
        width: 28,
        height: 6,
        rx: 3,
        fill: palette.shadow,
        stroke: palette.stroke,
        strokeWidth: 4,
      }),
    ]),
};

export default function PieceSprite({ piece, className = "h-12 w-12", tone = "board" }) {
  if (!piece) return null;
  const key = piece.toLowerCase();
  const sprite = SPRITES[key];
  if (!sprite) return null;
  const palette = piece === piece.toUpperCase() ? WHITE_PALETTE : BLACK_PALETTE;
  const classes = ["inline-flex items-center justify-center", className, tone === "board" ? "drop-shadow" : ""]
    .filter(Boolean)
    .join(" ");
  return createElement("span", { className: classes }, sprite(palette));
}
